global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: laravel-s-test
    honor_timestamps: true
    metrics_path: /actuator/prometheus
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - php:5200
  - job_name: laravel-nginx
    honor_timestamps: true
    metrics_path: /actuator/prometheus
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - nginx:80
